/*
 * Copyright (c) 2026 htjulia <htjulia1@gmail.com>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package org.htcom.protean.module;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * ModuleStoreDialect resolution (Docker-free): the three built-ins are registered, strict product-name detection maps
 * only exactly-known vendors, an explicit override wins (with the postgres alias), consumer beans override/extend by
 * id, and an unmatched or malformed dialect fails fast with an actionable message.
 */
class ModuleStoreDialectsTest {

    private static Map<String, ModuleStoreDialect> builtins() {
        return ModuleStoreDialects.registry(List.of());
    }

    @Test
    void registry_has_the_three_builtins() {
        Map<String, ModuleStoreDialect> r = builtins();
        assertInstanceOf(H2StoreDialect.class, r.get("h2"));
        assertInstanceOf(MySqlStoreDialect.class, r.get("mysql"));
        assertInstanceOf(PostgresStoreDialect.class, r.get("postgresql"));
        assertEquals("LONGTEXT", r.get("mysql").jsonTextColumnType());
        assertEquals("TEXT", r.get("postgresql").jsonTextColumnType());
        assertEquals("CLOB", r.get("h2").jsonTextColumnType());
        assertEquals("BIGSERIAL PRIMARY KEY", r.get("postgresql").autoIncrementColumnDefinition());
    }

    @Test
    void detect_maps_only_exactly_known_vendors() {
        assertEquals("h2", ModuleStoreDialects.detect("H2"));
        assertEquals("mysql", ModuleStoreDialects.detect("MySQL"));
        assertEquals("postgresql", ModuleStoreDialects.detect("PostgreSQL 15.2"));
        assertNull(ModuleStoreDialects.detect("MariaDB"), "strict mode: MariaDB is not auto-mapped");
        assertNull(ModuleStoreDialects.detect("Oracle"));
        assertNull(ModuleStoreDialects.detect(null));
    }

    @Test
    void override_wins_and_postgres_alias_resolves() {
        assertInstanceOf(MySqlStoreDialect.class,
                ModuleStoreDialects.resolve(builtins(), "mysql", "H2"), "override beats detection");
        assertInstanceOf(PostgresStoreDialect.class,
                ModuleStoreDialects.resolve(builtins(), "postgres", null), "postgres is an alias for postgresql");
    }

    @Test
    void detection_used_when_override_blank() {
        assertInstanceOf(PostgresStoreDialect.class,
                ModuleStoreDialects.resolve(builtins(), "  ", "PostgreSQL 16.1"));
        assertInstanceOf(H2StoreDialect.class,
                ModuleStoreDialects.resolve(builtins(), null, "H2"));
    }

    @Test
    void unmatched_vendor_fails_fast_with_guidance() {
        // Unknown detected vendor
        IllegalStateException detected = assertThrows(IllegalStateException.class,
                () -> ModuleStoreDialects.resolve(builtins(), null, "Oracle"));
        assertTrue(detected.getMessage().contains("Oracle"));
        assertTrue(detected.getMessage().contains("10-spi-extension"), "must point to the SPI doc");

        // Unknown explicit override
        IllegalStateException requested = assertThrows(IllegalStateException.class,
                () -> ModuleStoreDialects.resolve(builtins(), "oracle", "Oracle"));
        assertTrue(requested.getMessage().contains("module-store.dialect"));
        assertTrue(requested.getMessage().contains("[h2, mysql, postgresql]"), "lists available ids");
    }

    @Test
    void consumer_bean_overrides_builtin_and_adds_vendor() {
        ModuleStoreDialect fakeMysql = dialect("mysql", "JSON", "BIGINT AUTO_INCREMENT PRIMARY KEY");
        ModuleStoreDialect oracle = dialect("oracle", "CLOB", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        Map<String, ModuleStoreDialect> r = ModuleStoreDialects.registry(List.of(fakeMysql, oracle));

        assertEquals("JSON", r.get("mysql").jsonTextColumnType(), "same id() overrides the built-in");
        assertInstanceOf(H2StoreDialect.class, r.get("h2"), "untouched built-ins remain");
        assertEquals(oracle, ModuleStoreDialects.resolve(r, "oracle", null), "new vendor is selectable");
    }

    @Test
    void blank_token_dialect_is_rejected() {
        ModuleStoreDialect bad = dialect("bad", "  ", "BIGINT AUTO_INCREMENT PRIMARY KEY");
        Map<String, ModuleStoreDialect> r = ModuleStoreDialects.registry(List.of(bad));
        IllegalStateException e = assertThrows(IllegalStateException.class,
                () -> ModuleStoreDialects.resolve(r, "bad", null));
        assertTrue(e.getMessage().contains("non-blank"));
    }

    private static ModuleStoreDialect dialect(String id, String jsonType, String autoInc) {
        return new ModuleStoreDialect() {
            @Override public String id() { return id; }
            @Override public String jsonTextColumnType() { return jsonType; }
            @Override public String autoIncrementColumnDefinition() { return autoInc; }
        };
    }
}
